### ISSUE TITLE
Multiple tally receivers?

### ISSUE THREAD

**Issue by DaanCMP** [hennedo/wifitally#3]
Hi!
Does this project support multiple receivers?

Lets say i have camera's with operators on input 4, 5 and 6. Can i send transmit all tallys with one ardiuno, and receive with 3 esp's?

I have knowledge of arduino, so i can understand your code.

best regards, Daniël

**Comment by hennedo** [comment]
Hey Daniël,
yes! The codebase supports up to 8 input tally signals and an unlimited number of esp's receiving them.
